### ISSUE TITLE
android app comes up with a message "Invalid transaction StntaxError: JSON Parse error: Unable to p...." every 15 seconds or so

### ISSUE THREAD

**Issue by debris** [paritytech/native-signer#48]

**Comment by debris** [comment]
@tomusdrw can you check that? :/

**Comment by tomusdrw** [comment]
I'm getting this error when scanning an address QR code instead of transaction QR.
I think the solution will be:
1. If address is detected display a message that you should scan transaction instead of address (but only for the first time).
2. Later ignore all invalid QR codes found (or just display a toast/non-blocking notification instead of blocking message).
